---
title: "NTOLab13"
authors: "NTO"
date: "4/16/2019"
output: html_document
---

```{r,echo=FALSE, include=FALSE}
library(tidyverse)
library(lubridate)
library(stringr)

perm_mean <- function(perms, values, n1)
{
## step one
  result <- vector("numeric", perms)
  
  # Loop throught number of permutations
  for (i in 1:perms)
  {
    x <- sample(1:length(values), n1)
  
  group1 <- values[x]
  group2 <- values[-x]

  diff <- mean(group1)-mean(group2)
  result[i] <- diff
    # Step 4:

  }
  # Step 5:
 result <- as.tibble(result)
 #print(result)
}

perm_cor <- function(perms,x,y){
  result <- vector("numeric",perms)

for( i in c(1:perms))
{
  y <- sample(y,length(y))
  c <- cor(x,y)
  result[i] <- c
}
result <- as.tibble(result)
}

#paste csvs here

#Ethan csvs
math <- read_csv("math_achievement_8th_grade.csv")
out_of_school <- read_csv("children_out_of_school_primary.csv")

#Arie's Csv
MeanYears25to34 <- read_csv("mean_years_in_school_women_percent_men_25_to_34_years.csv")
Literacy <- read_csv("primary_completion_rate_total_percent_of_relevant_age_group.csv")
```

****
#### Team Section
****

```{r,echo = FALSE}

```

****
#### Arie's Subquestion
****

```{r,echo = FALSE, warning=FALSE, message=FALSE}

### merge/tidy ###
Q <- inner_join(MeanYears25to34, Literacy, by = "country")%>%select(c(country, `1999.x`, `2015.x`, `1999.y`, `2015.y`))%>%
  filter(!is.na(`1999.y`), !is.na(`2015.y`), country == "Switzerland"| country == "South Korea" | country == "Sweden" | country == "Belize" | country == "Colombia" | country == "Cuba" | country == "Ethiopia" | country == "Guatemala" | country == "Ghana" | country == "India" | country == "Mexico"| country == "Venezuela" | country == "Palestine" | country == "Italy" | country == "Austria")

### ggplot ###

ggplot(data = Q)+geom_line(mapping = aes(x = `1999.x`, y = `1999.y`, color = "1999"))+geom_line(mapping = aes(x = `2015.x`, y = `2015.y`, color = "2015"))+
  geom_smooth(mapping = aes(x = `1999.x`, y = `1999.y`), method = "lm", se = FALSE, size = .5, color = "black")+geom_smooth(mapping = aes(x = `2015.x`, y = `2015.y`), method = "lm", se = FALSE, size = .5, color = "black")+
  xlab("Gender Ratio of mean years in school (% Ages 25-34)")+ylab("Primary School Completion (%)")+ggtitle("Average years in school vs. Primary school completion")
```

```{r,echo = FALSE, warning=FALSE, message=FALSE}
### actual correlation ###
bb1999 <- cor(Q$`1999.x`, Q$`1999.y`)

bb2015<- cor(Q$`2015.x`, Q$`2015.y`)

Q = as.tibble(Q)

corr1999 <- perm_cor(1000,Q$`1999.x`, Q$`1999.y`)
ccp95 <- quantile(corr1999$value, .95)
ccP5 <- quantile(corr1999$value, .05)

corr2015 <- perm_cor(1000,Q$`2015.x`, Q$`2015.y`)
cc95 <- quantile(corr2015$value, .95)
cc5 <- quantile(corr2015$value, .05)

### ggplot correlation permutation test ###

ggplot(data=corr1999, mapping = aes(x=value))+
  geom_histogram(size = 1)+
  geom_vline(xintercept = ccp95, color="red", size = 1) +
  geom_text(aes(x = ccp95, y = 3, label = "95th Percentile")) +
  geom_vline(xintercept = bb1999, color="blue", size = 1) +
  geom_text(aes(x = bb1999, y = 3, label = "Actual")) +
  geom_vline(xintercept = ccP5, color="red", size = 1) +
  geom_text(aes(x = ccP5, y = 3, label = "5th Percentile")) +
  xlab("Correlation Constant") +
  ylab("Count") +
  ggtitle("Correlation Permutation Test for Average years in school vs. Primary school completion in 1999")

```

****
#### Ethan's Subquestion
****

```{r,echo = FALSE}

#Data Merging / Transformation

countries <- gapminder::gapminder_unfiltered %>%
  filter(year == 2007) %>%
  select(country, pop) #Need population value for my countries to get proportions

merged <- inner_join(math, out_of_school, by = "country") %>%
  filter(!is.na(`2007.x`) & !is.na(`2007.y`)) %>% #gets countries for these years with no NA's
  mutate(math_scores_2007 = `2007.x`) %>%
  mutate(outofschool_2007 = `2007.y`) %>%
  select(country, math_scores_2007, outofschool_2007)

merged2 <- inner_join(merged, countries, by = "country") %>%
  mutate(out_of_school_perc = outofschool_2007 / pop) #creates proportion variable

#Scatter Plot

ggplot(data = merged2) +
  geom_point(mapping = aes(x = out_of_school_perc, y = math_scores_2007)) +
  xlab("Percentage of Country Population that are Children out of School") +
  ylab("Average TIMSS Score") +
  ggtitle("Proportion of Children out of School vs. Math Achievement of 8th Graders") +
  geom_text(mapping = aes(out_of_school_perc, y = math_scores_2007, 
            label = ifelse(math_scores_2007 < 360 | out_of_school_perc > 0.01 | country %in% c("Japan", "United Kingdom", "Italy", "Australia"), country, ""),
            hjust = ifelse(out_of_school_perc < 0.04, -0.15, 1.15), vjust = 0))

#Permutation test

corr <- perm_cor(1000,merged2$out_of_school_perc, merged2$math_scores_2007) 
c_95 <- quantile(corr$value,.95) #0.281
c_05 <- quantile(corr$value,.05) #-0.294
actual <- cor(merged2$out_of_school_perc,merged2$math_scores_2007) #-0.47

ggplot(data=corr,mapping = aes(x=value))+
  geom_histogram(size = 1)+
  geom_vline(xintercept = c_95, color="red", size = 1) +
  geom_text(aes(x = c_95, y = 50, label = "95th Percentile")) +
  geom_vline(xintercept = actual, color="blue", size = 1) +
  geom_text(aes(x = actual, y = 50, label = "Actual")) +
  geom_vline(xintercept = c_05, color="red", size = 1) +
  geom_text(aes(x = c_05, y = 50, label = "5th Percentile")) +
  xlab("Correlation Constant") +
  ylab("Count") +
  ggtitle("Correlation Permutation Test for Children not in School vs. Math Scores")

```

****
#### Anderson's Subquestion
****

```{r,echo = FALSE}

```

****
#### David's Subquestion
****

```{r,echo = FALSE}

```

****
#### Ryan's Subquestion
****

```{r,echo = FALSE}

```

****
#### Who Did What
****

* David -
* Arie - 
* Anderson - 
* Ethan -
* Ryan -